### PR TITLE
Use dpl for gem deployment

### PR DESCRIPTION
**Pull request by kzaitsev**
Why not ¯_(ツ)_/¯

### CODE REVIEW

**Comment by tboerger** [comment]
@Bugagazavr you have seen my go implementation that invokes dpl? ;)

**Comment by kzaitsev** [comment]
@tboerger no

**Comment by tboerger** [comment]
https://github.com/drone-plugins/drone-rubygems/pull/1 :D

**Comment by bradrydzewski** [comment]
@tboerger looks like it didn't grab the right logo file ... try `http://svgporn.com/logos/rubygems.svg`

**Comment by bradrydzewski** [comment]
other than that, LGTM

**Comment by tboerger** [comment]
As https://github.com/drone-plugins/drone-rubygems/pull/1 have been merged I will close that for now.

**Pull request closed without merging**
