### PR TITLE
Initial implementation based on dpl

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by kzaitsev** [comment]
LGTM

**Comment by bradrydzewski** [comment]
@tboerger looks like it didn't grab the right logo file ... try http://svgporn.com/logos/rubygems.svg

**Comment by bradrydzewski** [comment]
other than that, LGTM

**Comment by kzaitsev** [comment]
LGTM

**Comment by tboerger** [comment]
@Bugagazavr verified that it's working, merging it now.

**Pull request merged**
