### PR TITLE
Unification: Drone config, Makefile, structure and badges

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by jackspirou** [comment]
LGTM

**Comment by kzaitsev** [comment]
LGTM

**Comment by kzaitsev** [comment]
@bradrydzewski looks like you need update drone.sec

**Comment by tboerger** [comment]
> @bradrydzewski looks like you need update drone.sec

`drone.sec` should be fine, but it looks like I don't have enough permissions to push with my user (which is set within the updated .drone.sec).

**Pull request merged**
